name: build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
  
    - name: Install PCL
      run: sudo apt-get install libpcl-dev

    - name: Configure CMake
      run: cmake -B ${{dir}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{dir}}/build --config Release
      
    - name: Test
      run: build/pointcloudToMESH
